[package]
name = "worky-common"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
deno_core = { workspace = true }
futures = { workspace = true }
