[package]
name = "worky-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
worky-api = { path = "../worky-api" }
worky-runtime = { path = "../worky-runtime" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
