[package]
name = "worky-cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
worky-api = { path = "../worky-api" }
worky-runtime = { path = "../worky-runtime" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
