[package]
name = "worky-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
worky-common = { path = "../worky-common" }
worky-ops = { path = "../worky-ops" }
deno_core = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
